const routes = require('express').Router();
const {disAssociatePermissionSet} = require('./services/disassociatePermission');
const {fetchAllPermissions} = require('./services/fetchAllPermissions');
const {associatePermissionSet} = require('./services/associatePermission');
const {getPermissionDocument} = require('./services/permissionDoc');
routes.get('/shared/permission/permission-document-all', getPermissionDocument);
routes.get('/shared/permission/permission/all', fetchAllPermissions);
routes.post('/shared/permission/associate', associatePermissionSet);
routes.post('/shared/permission/disassociate', disAssociatePermissionSet);
module.exports = routes;
